#!/usr/bin/env python3
# Copyright 2009-2017 BHG http://bw.org/

import turtle

screen = turtle.Screen()
screen.bgcolor("yellowgreen")
screen.title("Circle")

my_turtle = turtle.Turtle()
my_turtle.pensize(5)
my_turtle.shape("circle")
my_turtle.forward(100)
for i in range(0, 8):
    my_turtle.forward(100)
    my_turtle.backward(100)
    my_turtle.left(45)
    print(screen)

