#!/usr/bin/env python3
# Copyright 2009-2017 BHG http://bw.org/

## joining strings together:

continents = "Asia, Europe, Africa, Australia, Antarctica";
combine = "".join(continents);
print(combine)
