#!/usr/bin/env python3
# Copyright 2009-2017 BHG http://bw.org/

import random

## Finds number of multiples of a number

num = int(input("What number do you want to find?\n"))

count = 0;
for j in range(1, 100):
    for i in range(j, 100):
        if (i * j == num):
            count += 1;
        
print("Num of multiples:",count);
