#!/usr/bin/env python3
# Copyright 2009-2017 BHG http://bw.org/

## Palindrome

def palindrome(word):
    for i in range(1, len(word)+1):
        if word[i-1] == word[-i]:
            continue
        else:
            return False
    return True

word = str(input("Enter a word:\n"))
if palindrome(word) == True:
    print("The word is a palindrome.")
else:
    print("The word is not a palindrome.")
