#!/usr/bin/env python3
# Copyright 2009-2017 BHG http://bw.org/

## Getting rid of given words in a given phrase

def remove(str1):
    listStr = str1.split();
    removeWords = [];
    newList = [];
    wordRemove = input("What word do you want to remove?\n");
    removeWords.append(wordRemove);
    
    ## Removing as many words as user says
    while True:
        playAgain = input("Want to remove more words?\n");
        if playAgain[0].lower() == 'y':
            wordRemove = input("What word do you want to remove?\n");
            removeWords.append(wordRemove);
        else:
            break;
    
    ## Checking if any word in original string = UNEXISTABLE words
    for i in listStr:
        for j in removeWords:
            if i == j:
                continue
            else:
                newList.append(i)
    ## Making list into an actual sentence
    return ' '.join(newList);
    
str1 = input("Enter a phrase:\n");
print(remove(str1));
